# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f2f5065ccc80e562192fc1611d08c1d0a3e463b2043e66aabbca3eab102264b9e65033cd938686e995cfc0a9db599cb25139dac1efc7677c080d544452219fc

test:
  secret_key_base: 869eb7092164d9305123c85d77718b3313565f4a54df01354fa13208d8cebcbe7e7de312f83df0577a99c3302560121f421636bdd68c2d29cb4fe1c9b7aad4e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
