# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: caffb7f2914e9dd36ffd1a70c2fa8733312030bdbdc10a1591fd57420682a0fd258e49409b2559dc366401e058cbda6673891e000a44423fc4bb7adbaffc2e46
  stripe_publishable_key: pk_test_eNf41km4qob9JPZmiA9C6iyt
  stripe_secret_key: sk_test_Gdtktj5q8UkAkILx4rpzNFXI
test:
  secret_key_base: a2aa5e3c7417e03f76b8991272e6ef16de126feaabf9319bc3a4f546d9e90f297c48dd2fea0b3730465b2f03489a1a00ec3677bebe93144b927283145453fb30
  stripe_publishable_key: pk_test_eNf41km4qob9JPZmiA9C6iyt
  stripe_secret_key: sk_test_Gdtktj5q8UkAkILx4rpzNFXI
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
